---
- name: Deploy Scientific Calculator Application with Ansible
  hosts: localhost
  connection: local
  become: yes

  vars:
    # Default to the current directory, but allow override from Jenkins
    project_root: "{{ lookup('env', 'WORKSPACE') | default('.', true) }}"
    backend_image_name: "deathlymade/spe-backend"
    frontend_image_name: "deathlymade/spe-frontend"
    backend_container_name: "sci-calc-backend-dev"
    frontend_container_name: "sci-calc-frontend-dev"
    app_network: "sci-calc-net"

  tasks:
    - name: DEBUG - Print the project root path
      ansible.builtin.debug:
        msg: "Building from project root: {{ project_root }}"

    - name: DEBUG - List files in the project root
      command: ls -la "{{ project_root }}"
      register: file_list
    
    - name: DEBUG - Show file listing
      ansible.builtin.debug:
        var: file_list.stdout_lines

    - name: Install required Python libraries for Ansible Docker modules
      pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create Docker volumes
      community.docker.docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - m2-repo
        - frontend_node_modules

    - name: Create a dedicated network for the application
      community.docker.docker_network:
        name: "{{ app_network }}"
        state: present

    - name: Build the backend image
      community.docker.docker_image:
        name: "{{ backend_image_name }}"
        build:
          # Use the absolute path from the WORKSPACE variable
          path: "{{ project_root }}"
          dockerfile: backend.Dockerfile
        source: build
        state: present
        # Force a rebuild if the source code changes, good for CI
        force_source: yes
      register: backend_image

    - name: Run the backend container
      community.docker.docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ backend_image_name }}"
        state: started
        recreate: yes
        volumes:
          - "{{ project_root }}/:/app/backend:delegated"
          - "m2-repo:/root/.m2/repository"
        ports:
          - "8081:8081"
        env:
          SPRING_PROFILES_ACTIVE: "dev"
        networks:
          - name: "{{ app_network }}"
            aliases:
              - backend

    - name: Build the frontend image
      community.docker.docker_image:
        name: "{{ frontend_image_name }}"
        build:
          # Use the absolute path from the WORKSPACE variable
          path: "{{ project_root }}"
          dockerfile: frontend.Dockerfile
        source: build
        state: present
        # Force a rebuild if the source code changes
        force_source: yes
      register: frontend_image

    - name: Run the frontend container
      community.docker.docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ frontend_image_name }}"
        state: started
        recreate: yes
        # We remove the application code bind mount.
        # The code is now INSIDE the image.
        volumes:
          # We ONLY keep the named volume for node_modules to preserve it if needed,
          # though with `npm ci` it's less critical. Can be removed if you prefer.
          # test comment2
          - "frontend_node_modules:/frontend/node_modules"
        ports:
          - "5173:5173"
        env:
          CHOKIDAR_USEPOLLING: "true"
          BROWSER: "none"
        networks:
          - name: "{{ app_network }}"
        command: ["npm", "run", "dev"]