---
- name: Deploy Scientific Calculator Application with Ansible
  hosts: localhost
  connection: local
  become: yes

  vars:
    backend_image_name: "deathlymade/spe-backend"
    frontend_image_name: "deathlymade/spe-frontend"
    backend_container_name: "sci-calc-backend-dev"
    frontend_container_name: "sci-calc-frontend-dev"
    app_network: "sci-calc-net"

  tasks:
    - name: Install required Python libraries for Ansible Docker modules
      pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create Docker volumes
      docker_volume:
        name: "{{ item }}"
        state: present
      loop:
        - m2-repo
        - frontend_node_modules

    - name: Create a dedicated network for the application
      docker_network:
        name: "{{ app_network }}"
        state: present

    - name: Build the backend image
      docker_image:
        name: "{{ backend_image_name }}"
        build:
          path: .
          dockerfile: backend.Dockerfile
        source: build
        state: present
      register: backend_image

    - name: Run the backend container
      docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ backend_image_name }}"
        state: started
        recreate: yes
        volumes:
          - "./:/app/backend:delegated"
          - "m2-repo:/root/.m2/repository"
        ports:
          - "8081:8081"
        env:
          SPRING_PROFILES_ACTIVE: "dev"
        networks:
          - name: "{{ app_network }}"
            aliases:
              - backend

    - name: Build the frontend image
      docker_image:
        name: "{{ frontend_image_name }}"
        build:
          path: .
          dockerfile: frontend.Dockerfile
        source: build
        state: present
      register: frontend_image

    - name: Run the frontend container
      docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ frontend_image_name }}"
        state: started
        recreate: yes
        volumes:
          - "./frontend/science-calc:/frontend:delegated"
          - "frontend_node_modules:/frontend/node_modules"
        ports:
          - "5173:5173"
        env:
          CHOKIDAR_USEPOLLING: "true"
          BROWSER: "none"
        networks:
          - name: "{{ app_network }}"
        command: ["npm", "run", "dev"]